apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: road-sign-ml
  labels:
    app: mlflow
    component: tracking-server
spec:
  type: ClusterIP
  selector:
    app: mlflow
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-postgres-service
  namespace: road-sign-ml
  labels:
    app: mlflow-postgres
    component: database
spec:
  type: ClusterIP
  selector:
    app: mlflow-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
