# Configuration MLflow - Tracking et modèles
tracking_uri: "http://localhost:5000"
default_artifact_root: "./mlruns"
backend_store_uri: "sqlite:///mlflow.db"

# Experiments principaux
experiments:
  road_sign_detection:
    name: "RoadSign_Detection_YOLOv8"
    description: "Entraînement et évaluation des modèles YOLO pour détection de panneaux"
    tags:
      - computer_vision
      - yolo
      - detection
      - traffic_signs
    
  ocr_recognition:
    name: "RoadSign_OCR_Recognition" 
    description: "Reconnaissance de texte sur panneaux détectés"
    tags:
      - ocr
      - tesseract
      - text_recognition
      - traffic_signs
      
  end_to_end_pipeline:
    name: "RoadSign_E2E_Pipeline"
    description: "Pipeline complet détection + OCR"
    tags:
      - pipeline
      - production
      - inference

# Configuration des modèles
models:
  yolo_detection:
    name: "road_sign_yolo_detector"
    description: "Modèle YOLO fine-tuné pour détecter les panneaux routiers"
    model_type: "detection"
    framework: "ultralytics"
    
  ocr_engine:
    name: "road_sign_ocr_reader"
    description: "Moteur OCR optimisé pour la lecture de texte sur panneaux"
    model_type: "ocr"
    framework: "tesseract"

# Métriques à tracker
metrics:
  detection:
    - "map50"           # Mean Average Precision @ IoU=0.5
    - "map50_95"        # Mean Average Precision @ IoU=0.5:0.95
    - "precision"       # Précision moyenne
    - "recall"          # Rappel moyen
    - "f1_score"        # F1-Score
    - "inference_time"  # Temps d'inférence (ms)
    
  ocr:
    - "character_accuracy"  # Précision caractère
    - "word_accuracy"       # Précision mot
    - "edit_distance"       # Distance d'édition
    - "confidence_score"    # Score de confiance moyen
    - "processing_time"     # Temps de traitement (ms)
    
  pipeline:
    - "end_to_end_accuracy"  # Précision bout en bout
    - "total_processing_time" # Temps total pipeline
    - "throughput"           # Images/seconde

# Paramètres par défaut
default_parameters:
  yolo:
    epochs: 100
    batch_size: 16
    img_size: 640
    lr0: 0.01
    weight_decay: 0.0005
    
  data:
    train_split: 0.8
    val_split: 0.1 
    test_split: 0.1
    augmentation: true
    
  preprocessing:
    normalize: true
    resize_mode: "letterbox"
    
# Artifacts à sauvegarder
artifacts:
  - "model_weights"      # Poids du modèle (.pt, .onnx)
  - "training_plots"     # Courbes d'entraînement
  - "confusion_matrix"   # Matrices de confusion
  - "sample_predictions" # Échantillons de prédictions
  - "model_config"       # Configuration du modèle
  - "preprocessing_config" # Configuration preprocessing
  - "evaluation_report"  # Rapport d'évaluation détaillé

# Configuration environnement
environment:
  python_version: "3.10"
  cuda_version: "12.1"
  pytorch_version: "2.3.0"
  ultralytics_version: "8.2.18"
