apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: road-sign-ml
  labels:
    app: road-sign-ml
    component: storage
    type: models
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: road-sign-ml
  labels:
    app: road-sign-ml
    component: storage
    type: data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: road-sign-ml
  labels:
    app: road-sign-ml
    component: storage
    type: logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
